// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"go-ddd-sample/application/service"
	"go-ddd-sample/dao/mysql"
	"go-ddd-sample/domain/repository"
	service2 "go-ddd-sample/domain/service"
)

// Injectors from wire.go:

func GetMemberService() *service.MemberService {
	db := mysql.GetDB()
	memberRepositoryMySQL := repository.NewMemberRepositoryMySQL(db)
	memberDomainServiceImpl := service2.NewMemberDomainServiceImpl()
	memberService := service.NewMemberService(memberRepositoryMySQL, memberDomainServiceImpl)
	return memberService
}

// wire.go:

var memberRepositorySet = wire.NewSet(repository.NewMemberRepositoryMySQL, wire.Bind(new(repository.MemberRepository), new(*repository.MemberRepositoryMySQL)), mysql.GetDB)

var memberServiceSet = wire.NewSet(service2.NewMemberDomainServiceImpl, wire.Bind(new(service2.MemberDomainService), new(*service2.MemberDomainServiceImpl)))
